POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer insert token here

{
    "title": "It was a very nice june",
    "author": "AAAAAAAAAAAAAAA",
    "url": "www.chungusbay.com",
    "likes": 0
}