POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wYXBwbGUiLCJpZCI6IjY4NTk0MzNlNDM4YmU0YjVhZDE3YTZkZSIsImlhdCI6MTc1MDY4NjkyMH0.nym_6kux1s4Khi2iiGVDqb--5d4rL5O5vPvRi-F3K6Q

{
    "title": "It was a very nice june",
    "author": "AAAAAAAAAAAAAAA",
    "url": "www.chungusbay.com",
    "likes": 0
}